<a href="https://colab.research.google.com/github/kurtlang123/CSST101-LAB/blob/main/Larioza%2C_John_Kurt_BSCS_3A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print ("I love R Prog")

[1] "I love R Prog"

In [4]:
name <- "Kurt"         # Character (String)
age <- 18               # Numeric (Double)
count <- 10L            # Integer (L specifies integer)
is_student <- TRUE      # Logical (Boolean)

# Printing variables and checking their data types
print(name)
class(name)

print(age)
class(age)

print(is_student)
class(is_student)

[1] "Kurt"

[1] "character"

[1] 18

[1] "numeric"

[1] TRUE

[1] "logical"

In [5]:
# Numerical variables
x <- 10.5
y <- 3

# Basic arithmetic operations
add <- x + y   # Addition
sub <- x - y   # Subtraction
mul <- x * y   # Multiplication
div <- x / y   # Division
mod <- x %% y  # Modulus
exp <- x ^ y   # Exponentiation

print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

[1] 13.5
[1] 7.5
[1] 31.5
[1] 3.5
[1] 1.5
[1] 1157.625

In [6]:
user_name <- readline(prompt = "Enter your name: ")

# Prompting for a numeric input (converted from string to numeric)
user_age <- as.numeric(readline(prompt = "Enter your age: "))

# Displaying the input back to the user
print(paste("Hello,", user_name, "! You are", user_age, "years old."))

# Performing a simple calculation with the input
years_to_hundred <- 100 - user_age
cat(user_name, "will turn 100 in", years_to_hundred, "years!\n")

Enter your name: kurt
Enter your age: 20
[1] "Hello, kurt ! You are 20 years old."
kurt will turn 100 in 80 years!

In [7]:
score <- 75

# Basic if...else statement
if (score >= 75) {
  print("Status: Passed")
} else {
  print("Status: Failed")
}

# Multiple conditions using if...else if...else
if (score >= 90) {
  grade <- "A"
} else if (score >= 80) {
  grade <- "B"
} else if (score >= 70) {
  grade <- "C"
} else {
  grade <- "F"
}

cat("Grade:", grade, "\n")

# Vectorized condition using ifelse()
# Great for quick checks or applying logic across vectors!
status <- ifelse(score >= 75, "High Distinction", "Standard Pass")
print(status)

[1] "Status: Passed"
Grade: C
[1] "High Distinction"

In [8]:
for(i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

In [9]:
addnum <- function(a,b){
  return (a+b)
}
addnum(3,7)

[1] 10

In [10]:
grades <- c(98,80,91,88,96)

grades

cat ("Mean:",mean(grades))
cat ("\nMax:",max(grades))
cat ("\nMin:",min(grades))
cat ("\nLength:",length(grades))
cat ("\nMedian:",median(grades))
summary(grades)

[1] 98 80 91 88 96

Mean: 90.6
Max: 98
Min: 80
Length: 5
Median: 91

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   80.0    88.0    91.0    90.6    96.0    98.0

In [11]:
A <-matrix(c(1,2,3,4,5,6),nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

In [13]:
Student <- list(
  name= "Jeff",
  course= "BSCS",
  grade = 75
)
Student

$name
[1] "Jeff"

$course
[1] "BSCS"

$grade
[1] 75

In [14]:
Student <- data.frame(
  name = c("kim","sam","Anna"),
  course = c("BSCS","BSIT","BSA"),
  grade = c(75,80,79)
)
Student

  name course grade
1 kim  BSCS   75
2 sam  BSIT   80
3 Anna BSA    79

In [15]:
write.csv(Student,"students.csv")

In [17]:
data <- read.csv("students.csv")

head(data)
summary(data)

  X name course grade
1 1 kim  BSCS   75
2 2 sam  BSIT   80
3 3 Anna BSA    79

       X              name         course      grade
 Min.   :1.0   Length   :3   Length   :3   Min.   :75.0
 1st Qu.:1.5   N.unique :3   N.unique :3   1st Qu.:77.0
 Median :2.0   N.blank  :0   N.blank  :0   Median :79.0
 Mean   :2.0   Min.nchar:3   Min.nchar:3   Mean   :78.0
 3rd Qu.:2.5   Max.nchar:4   Max.nchar:4   3rd Qu.:79.5
 Max.   :3.0                               Max.   :80.0